dist: trusty
install: true
language: java
jdk:
- oraclejdk8
env:
  global:
  - DISPLAY=:99.0
  - secure: oR303ENm1sr6olUycBARDwmcJ4wWPrtCnixbVdiwFvGTuKvNIlQP/RMqjPN7ixa9ctO3du4yUhp+qRiCJSvbCCqL4pYcvVuyjtQpU8uwIm3TimcC3b/6lqf6v3mzYyiBeJ3zvSlbhJdIhDzH0Oslug8fXevJwewnieFEh22/vxX7wCcv9NfjMJe8L0aKmtq2Z43v1rR9Tf5dw2AhtTzlLkRTYHPKH2vrjGuBY5NRZ73LtDi9fmnaC+uvks446Mi9kToOte/8hN88a+QiOoIvII0rkXuMdWj1qPd1toRY30Kn5hyPughody50j4aAvYoLF4r9bMYPL5HEwP+jomzoXDwdruNq0oCusBNcoZFv8RHHLkr/3DA626gNubeLSHrBpK7r+Y2HPY+/q2dGVJtac7Y3CdaxNAd9dPHpQyOq4E4K5EfzBUpe/OBjwgOjUmiPV2AyX7ugBJZ+gezH68YIG3023yA2DayyGYMtQj6cyzP5BTnt4i3vqoyzz9vJkh9q9/fSc9pztJXgrO41Y67wLWutDdP5zPoioOpzvLpgnQBrDHjlg0uX9Prr0q62ArUVmRTVWpIaIN+yyDWJJd++Yc8No1RFazIFrbY/Hp3t0taBzIiWysPh/+uLdtfYvi82NL3wQOoTvc2eZaHIMX82Crj+OGc25iG4Yw2GWbxiHhA=
before_install:
- sudo apt-get install at-spi2-core
before_script:
- sh -e /etc/init.d/xvfb start
- sleep 10
script: mvn -f mavendeps/pom.xml p2:site && mvn clean verify
after_failure:
- cat $TRAVIS_BUILD_DIR/tests/org.codechecker.eclipse.rcp.it.tests/target/work/data/.metadata/.log
- cat $TRAVIS_BUILD_DIR/tests/org.codechecker.eclipse.rcp.it.tests/target/surefire-reports/*
- cat $TRAVIS_BUILD_DIR/tests/org.codechecker.eclipse.rcp.unit.tests/target/surefire-reports/*
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: releng/org.codechecker.eclipse.update/target/repository
  repo: vodorok/vodorok.github.io
  target-branch: master
  verbose: true
  on:
    branch: master
